<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->titulo. $this->translate('Logistica y control de claidad'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => '/img/logo.png', 'href' => $this->basePath() . '/img/logo.png'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')       
                        ->prependStylesheet($this->basePath() . '/css/modern-business.css')
                        ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css') ?>

        <!-- Scripts -->
        

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
         
        <div class="container">
           
            <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('sitio-inicio') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate(' CONEXPORT') ?></a>
                </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                
                <ul class="nav navbar-nav navbar-right">
                    
                    <li><a href="<?php echo $this->url('sitio-inicio') ?>"><i class="fa fa-home"></i><?php echo $this->translate(' Inicio') ?></a></li>
                        <li><a href="<?php echo $this->url('sitio-acerca') ?>"><i class="fa fa-thumbs-up"></i><?php echo $this->translate(' Quienes Somos') ?></a></li>
                        <li><a href="<?php echo $this->url('sitio-servicios') ?>"><i class="fa fa-globe"></i><?php echo $this->translate(' Servicios') ?></a></li>
                        <li><a href="<?php echo $this->url('sitio-contacto') ?>"><i class="fa fa-envelope"></i><?php echo $this->translate(' Contacto') ?></a></li>
                        <li><a href="#"><i class="fa fa-user"></i><?php echo $this->translate(' Ingreso de usuario') ?></a></li>
                       
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
        
            <?php echo $this->content; ?>
          
        <div class="container">
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p><?php echo $this->translate('Derechos reservados ') ?>  &copy; 2008 -  <?php echo date('Y') ?> Conexport Limitada. </p>
                </div>
            </div>
        </footer>

    </div>
        
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.js')
            ->prependFile($this->basePath() . '/js/modern-business.js')
            ->prependFile($this->basePath() . '/js/jquery-1.10.2.js')
            
        ; ?>
        
    </body>
</html>
