
 <?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Materiales';
 $subtitle= 'Materiales actuales';
 $this->headTitle($title);
 ?>
 
 
<div class="panel-heading">
    <?php echo $this->escapeHtml($title); ?>
</div>
<div class="panel-body">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary">
             <!-- Default panel contents -->
                <div class="panel-heading"><?php echo $this->escapeHtml($subtitle); ?> </div>
                    <div class="panel-body">
                        <p>Lista de materiales actualmente registrados. Eliga editar o Eliminar</p>
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Buscar...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
        <hr>
        <a class="btn btn-success btn-sm" href="<?php echo $this->url('admin-material', array('action'=>'agregar'));?>">Agregar nuevo material</a>
                    </div>

      <!-- Table -->
                    <div class="table-responsive">
          
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Codigo</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                            <?php foreach ($material as $m) : ?>
                            <tr>


                                <td><?php echo $this->escapeHtml($m->nombre);?></td>
                                <td><?php echo $this->escapeHtml($m->codigo);?></td>
                                <td>
                                    <a class="btn btn-warning btn-xs" href="<?php echo $this->url('admin-material',
                                        array('action'=>'editar', 'id_material' => $m->id_material));?>">Editar</a>
                                    <a class="btn btn-danger btn-xs" href="<?php echo $this->url('admin-material',
                                        array('action'=>'borrar', 'id_material' => $m->id_material));?>">Borrar</a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                    </tbody>
                 </table>        
           
                    </div>
                </div>
        </div>
    </div>
                                <!-- /.col-lg-6 (nested) -->
                                
                                <!-- /.col-lg-6 (nested) -->
</div>     