<div class="container">

        <div class="row">

            <div class="col-lg-12">
                <h1 class="page-header">Servicios
                    <small>Que hacemos</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="<?php echo $this->url('sitio-inicio') ?>">Inicio</a>
                    </li>
                    <li class="active">Servicios</li>
                </ol>
            </div>

        </div>
        <!-- /.row -->

        <div class="row">

            <div class="col-lg-12">
                <img class="img-responsive" src="<?php echo $this->basePath("img/servicios.jpg")?>">
            </div>

        </div>
        <!-- /.row -->

        <!-- Service Paragraphs -->
<!--
        <div class="row">

            <div class="col-md-8">
                <h2 class="page-header">Our Premium Services</h2>
                <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
            </div>

            <div class="col-md-4">
                <h2 class="page-header">Something More</h2>
                <p>Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets.</p>
                <a class="btn btn-primary" href="#">Click Me!</a>
            </div>

        </div> -->
        <!-- /.row -->

        <!-- Service Tabs -->

        <div class="row">

            <div class="col-lg-12">
                <h2 class="page-header">Nuestros servicios</h2>
                <ul id="myTab" class="nav nav-tabs">
                    <li class="active"><a href="#service-one" data-toggle="tab">Inspeccion de consolidados</a>
                    </li>
                    <li><a href="#service-two" data-toggle="tab">Inspección de carga.</a>
                    </li>
                    <li><a href="#service-three" data-toggle="tab">Otros</a>
                    </li>
                    
                    
                </ul>
                <div id="myTabContent" class="tab-content">
                    <div class="tab-pane fade in active" id="service-one">
                        
                        <p>Consiste en la supervisión del proceso de consolidado de madera para exportación, según norma de transporte internacional y solicitudes de los propios exportadores (dado su análisis de optimización de recursos o lo sugerido por nuestros supervisores).</p>
                        
                    </div>
                    <div class="tab-pane fade" id="service-two">
                     
                         <p>Consiste en la aplicación de procedimientos internacionales de inspección de calidad de productos forestales para la exportación, mediante la inspección in situ (planta, bodega o puerto) de los paquetes dispuestos para el cumplimiento de las respectivas ordenes de compras internacionales.</p>
                    </div>
                    <div class="tab-pane fade" id="service-three">
                       
                          <ul><li>Control de Calidad.</li>
<li>Inspección de carga para Exportación.</li>
<li>Inspección de carga de importación.</li>
<li>Surveyor, nacional e internacional.</li>
<li>Asesorías de Exportación.</li>
<li>Inspección de Consolidación / Desconsolidacion.</li>
                        </ul>
                    </div>
                    <div class="tab-pane fade" id="service-four">
                        <i class="fa fa-flask pull-left fa-4x"></i>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam placerat nunc ut tellus tristique, non posuere neque iaculis. Fusce aliquet dui ut felis rhoncus, vitae molestie mauris auctor. Donec pellentesque feugiat leo a adipiscing. Pellentesque quis tristique eros, sed rutrum mauris.</p>
                        <p>Nam fringilla quis enim in eleifend. Suspendisse sed lectus mauris. Nam commodo, arcu et posuere placerat, tellus tortor dignissim eros, sit amet eleifend urna lorem sit amet nulla. Praesent sem nibh, vulputate nec congue eu, dapibus vitae augue. Suspendisse cursus urna sit amet metus porttitor, in pharetra quam feugiat. Etiam tempus euismod nulla eget pellentesque.</p>
                    </div>
                    <div class="tab-pane fade" id="service-five">
                        <i class="fa fa-flag pull-left fa-4x"></i>
                        <p>Nam fringilla quis enim in eleifend. Suspendisse sed lectus mauris. Nam commodo, arcu et posuere placerat, tellus tortor dignissim eros, sit amet eleifend urna lorem sit amet nulla. Praesent sem nibh, vulputate nec congue eu, dapibus vitae augue. Suspendisse cursus urna sit amet metus porttitor, in pharetra quam feugiat. Etiam tempus euismod nulla eget pellentesque.</p>
                        <p>Vestibulum laoreet molestie urna ac vehicula. Phasellus laoreet semper ipsum ac gravida. Sed in varius tortor. Nullam blandit in neque quis aliquet. Fusce volutpat pellentesque sem non convallis. Suspendisse sit amet magna pulvinar, gravida mauris eu, tincidunt massa. Nam lectus mi, viverra non quam nec, mollis malesuada dolor. Vivamus hendrerit nunc interdum turpis egestas, a lobortis odio consequat. Fusce posuere purus quis ligula faucibus lacinia. Curabitur sit amet congue dolor. Duis dapibus hendrerit nunc et gravida. Phasellus mollis, lectus quis ornare aliquam, arcu orci posuere lectus, vehicula bibendum sem ante quis lacus.</p>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.row -->

        <!-- Service Images -->

        <div class="row">

            <div class="col-lg-12">
                <h2 class="page-header">Imagenes de servicios</h2>
            </div>

            <div class="col-sm-4">
                <img class="img-responsive" src="<?php echo $this->basePath("img/Servicios/controlCalidad.jpg")?>">
                <h3>Control de calidad</h3>
                
                <a class="btn btn-link btn-sm pull-right">Mas <i class="fa fa-angle-right"></i></a>
            </div>

            <div class="col-sm-4">
                <img class="img-responsive" src="<?php echo $this->basePath("img/Servicios/inspeccionCarga.jpg")?>">
                <h3>Inspeccion de carga</h3>
                
                <a class="btn btn-link btn-sm pull-right">Mas <i class="fa fa-angle-right"></i></a>
            </div>

            <div class="col-sm-4">
                <img class="img-responsive" src="<?php echo $this->basePath("img/Servicios/inspeccionConsolidacion.jpg")?>">
                <h3>Inspección de Consolidación / Desconsolidacion.</h3>
                
                <a class="btn btn-link btn-sm pull-right">Mas <i class="fa fa-angle-right"></i></a>
            </div>

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->