<div class="container">

        <div class="row">

            <div class="col-lg-12">
                <h1 class="page-header">Quienes somos
                    <small>Bienvenidos</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="<?php echo $this->url('sitio-inicio') ?>">Inicio</a>
                    </li>
                    <li class="active">Quienes somos</li>
                </ol>
            </div>

        </div>

        <div class="row">

            <div class="col-md-6">
                <img class="img-responsive" src="<?php echo $this->basePath("img/Conexport.jpg")?>">
            </div>
            <div class="col-md-6">
                <h2>Bienvenido a Conexport</h2>
                <p>Conexport Ltda, nace en el año 2008, como una iniciativa personal de sus socios, quienes habiéndose desempeñados en empresas de servicios para exportadores de maderas y a su vez en exportadoras multiproductos, observaron la creciente necesidad de servicios alternativos, específicos y profesionales relacionados con las cargas para exportaciones, es así como dan vida a una empresa que en el poco andar, logra posicionarse en el mercado Nacional e Internacional.</p>
            </div>

        </div>

        <!-- Team Member Profiles -->

        <div class="row">

            <div class="col-lg-12">
                <h2 class="page-header">Nuestro equipo</h2>
            </div>

            <div class="col-sm-4">
                <img class="img-responsive" src="<?php echo $this->basePath("img/equipo/gerente.jpg")?>">
                <h3>Jorge Luna B            
                </h3>
                <p> <h3><small>Gerente <br><a> <i class="fa fa-envelope-o fa-fw"></i> jorge.luna@conexport.cl</a></small></h3><hr></p>
                
            </div>

            <div class="col-sm-4">
                <img class="img-responsive" src="<?php echo $this->basePath("img/equipo/jefe.jpg")?>">
                <h3>Fabiola Cifuentes M          
                </h3>
                <p> <h3><small>Jefe de operaciones<br><a> <i class="fa fa-envelope-o fa-fw"></i> fabiola.cifuentes@conexport.cl</a></small></h3><hr></p>
                                
            </div>

            <div class="col-sm-4">
                <img class="img-responsive" src="<?php echo $this->basePath("img/equipo/sup.jpg")?>">
                <h3>Fernando Puga          
                </h3>
                <p> <h3><small>Coordinador <br><a> <i class="fa fa-envelope-o fa-fw"></i> fernando.puga@conexport.cl</a></small></h3><hr></p>
                
               
            </div>
<!--
            <div class="col-sm-3">
                <img class="img-responsive" src="img/equipo/Image_1.jpg">
                <h3>Supervisor2
                    <small>Supervisor 2</small>
                </h3>
                <p>Una pequeña descripcion de que realiza en la empresa.</p>
                <ul class="list-unstyled list-inline list-social-icons">
                    <li class="tooltip-social facebook-link"><a href="#facebook-profile" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook-square fa-2x"></i></a>
                    </li>
                    <li class="tooltip-social linkedin-link"><a href="#linkedin-profile" data-toggle="tooltip" data-placement="top" title="LinkedIn"><i class="fa fa-linkedin-square fa-2x"></i></a>
                    </li>
                    <li class="tooltip-social twitter-link"><a href="#twitter-profile" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter-square fa-2x"></i></a>
                    </li>
                    <li class="tooltip-social google-plus-link"><a href="#google-plus-profile" data-toggle="tooltip" data-placement="top" title="Google+"><i class="fa fa-google-plus-square fa-2x"></i></a>
                    </li>
                </ul>
            </div>

            <div class="col-sm-3">
                <img class="img-responsive" src="img/equipo/Image_1.jpg">
                <h3>Supervisor 3
                    <small>Supervisor 3</small>
                </h3>
                <p>Una pequeña descripcion de que realiza en la empresa.</p>
                <ul class="list-unstyled list-inline list-social-icons">
                    <li class="tooltip-social facebook-link"><a href="#facebook-profile" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook-square fa-2x"></i></a>
                    </li>
                    <li class="tooltip-social linkedin-link"><a href="#linkedin-profile" data-toggle="tooltip" data-placement="top" title="LinkedIn"><i class="fa fa-linkedin-square fa-2x"></i></a>
                    </li>
                    <li class="tooltip-social twitter-link"><a href="#twitter-profile" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter-square fa-2x"></i></a>
                    </li>
                    <li class="tooltip-social google-plus-link"><a href="#google-plus-profile" data-toggle="tooltip" data-placement="top" title="Google+"><i class="fa fa-google-plus-square fa-2x"></i></a>
                    </li>
                </ul>
            </div>

            <div class="col-sm-4">
                <img class="img-responsive" src="img/equipo/Image_1.jpg">
                <h3>Supervisor 4
                    <small>Supervisor 4</small>
                </h3>
                <p>Una pequeña descripcion de que realiza en la empresa.</p>
                <ul class="list-unstyled list-inline list-social-icons">
                    <li class="tooltip-social facebook-link"><a href="#facebook-profile" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook-square fa-2x"></i></a>
                    </li>
                    <li class="tooltip-social linkedin-link"><a href="#linkedin-profile" data-toggle="tooltip" data-placement="top" title="LinkedIn"><i class="fa fa-linkedin-square fa-2x"></i></a>
                    </li>
                    <li class="tooltip-social twitter-link"><a href="#twitter-profile" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter-square fa-2x"></i></a>
                    </li>
                    <li class="tooltip-social google-plus-link"><a href="#google-plus-profile" data-toggle="tooltip" data-placement="top" title="Google+"><i class="fa fa-google-plus-square fa-2x"></i></a>
                    </li>
                </ul>
            </div>

        </div>
-->
        <!-- Our Customers -->

        <div class="row">

            <div class="col-lg-12">
                <h2 class="page-header">Nuestros clientes</h2>
            </div>

            <div class="col-md-2 col-sm-4 col-xs-6">
                <img class="img-responsive img-customer img-thumbnail" src="<?php echo $this->basePath("img/clientes/arauco.png")?>">
            </div>

            <div class="col-md-2 col-sm-4 col-xs-6">
                <img class="img-responsive img-customer img-thumbnail" src="<?php echo $this->basePath("img/clientes/carbomat.jpg")?>">
            </div>

            <div class="col-md-2 col-sm-4 col-xs-6">
                <img class="img-responsive img-customer img-thumbnail" src="<?php echo $this->basePath("img/clientes/cmpc.jpg")?>">
            </div>

            <div class="col-md-2 col-sm-4 col-xs-6">
                <img class="img-responsive img-customer img-thumbnail" src="<?php echo $this->basePath("img/clientes/coronel.png")?>">
            </div>

            <div class="col-md-2 col-sm-4 col-xs-6">
                <img class="img-responsive img-customer img-thumbnail" src="<?php echo $this->basePath("img/clientes/maderasperu.jpg")?>">
            </div>

            <!--<div class="col-md-2 col-sm-4 col-xs-6">
                <img class="img-responsive img-customer img-thumbnail" src="img/clientes/pacifictrade.png">
            </div>-->

        </div>

    </div>
    <!-- /.container -->