  <div id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <div class="fill" style="background-image:url('<?php echo $this->basePath("img/slide.png")?>');"></div>
                <div class="carousel-caption">
                    <h1>Contról de calidad</h1>
                </div>
            </div>
            <div class="item">
                <div class="fill" style="background-image:url('<?php echo $this->basePath("img/slide.png")?>');"></div>
                <div class="carousel-caption">
                    <h1>Asesoría Exportaciones</h1>
                </div>
            </div>
            <div class="item">
                <div class="fill" style="background-image:url('<?php echo $this->basePath("img/slide.png")?>');"></div>
                <div class="carousel-caption">
                    <h1>Inspección de carga
                    </h1>
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>
    </div>

    <div class="section">

        <div class="container">

            <div class="row">
                <div class="col-lg-4 col-md-3">
                    <h3><i class="fa fa-check-circle"></i>Inspeccion de Consolidado</h3>
                    <p> Consiste en la supervisión del proceso de consolidado de madera para exportación, según norma de transporte internacional y solicitudes de los propios exportadores (dado su análisis de optimización de recursos o lo sugerido por nuestros supervisores).</p>
                </div>
               
                
                <div class="col-lg-4 col-md-3">
                    <h3><i class="fa fa-flag  pull-left"></i>Inspección de Calidad para productos de exportación.</h3>
                    <p>Consiste en la aplicación de procedimientos internacionales de inspección de calidad de productos forestales para la exportación, mediante la inspección in situ (planta, bodega o puerto) de los paquetes dispuestos para el cumplimiento de las respectivas ordenes de compras internacionales.</p>
                </div>
                 <div class="col-lg-4 col-md-3">
                    <h3><i class="fa fa-check-circle"></i>Otros servicios</h3>
                    <p>
                        <ul><li>Control de Calidad.</li>
<li>Inspección de carga para Exportación.</li>
<li>Inspección de carga de importación.</li>
<li>Surveyor, nacional e internacional.</li>
<li>Asesorías de Exportación.</li>
<li>Inspección de Consolidación / Desconsolidacion.</li>
                        </ul>
                    </p>   
                </div>
            </div>
            <!-- /.row -->

        </div>
        <!-- /.container -->

    </div>
    <!-- /.section -->

    <div class="section-colored text-center">

        <div class="container">

            <div class="row">
                <div class="col-lg-12 titulo-uno">
                    <h3>CONEXPORT LOGISTICA Y CONTROL DE CALIDAD</h3>
                    <p>MISION: Ser un aliado estratégico de nuestros clientes propendiendo al cumplimiento de las normas establecidas para el posicionamiento de sus productos en mercados nacionales e internacionales., con acento en nuestros principios empresariales que son; Compromiso, Calidad y Seriedad.</p>
                    <hr
                        <p>VISION: Ser referente nacional e internacional en materia de surveyor de exportación y control de calidad forestal.</p>
                </div>
            </div>
            <!-- /.row -->

        </div>
        <!-- /.container -->

    </div>
    <!-- /.section-colored -->

    <div class="section">

        <div class="container">

            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Nuestros servicios</h2>
                    <hr>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <a href="#">
                        <img class="img-responsive img-home-portfolio img-thumbnail" id="imagefront" src="<?php echo $this->basePath("img/Servicios/controlCalidad.jpg")?>">
                        
                    </a>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <a href="#">
                        <img class="img-responsive img-home-portfolio img-thumbnail" src="<?php echo $this->basePath("img/Servicios/inspeccionCarga.jpg")?>">
                    </a>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <a href="#">
                        <img class="img-responsive img-home-portfolio img-thumbnail" src="<?php echo $this->basePath("img/Servicios/surveryor.jpg")?>">
                    </a>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <a href="#">
                        <img class="img-responsive img-home-portfolio img-thumbnail" src="<?php echo $this->basePath("img/Servicios/asesoriaExportacion.jpg")?>">
                    </a>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <a href="#">
                        <img class="img-responsive img-home-portfolio img-thumbnail" src="<?php echo $this->basePath("img/Servicios/inspeccionConsolidacion.jpg")?>">
                    </a>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <a href="#">
                        <img class="img-responsive img-home-portfolio img-thumbnail" src="<?php echo $this->basePath("img/Servicios/desconsolidacion.jpg")?>">
                    </a>
                </div>
            </div>
            <!-- /.row -->

        </div>
        <!-- /.container -->

    </div>
    <!-- /.section -->

    <div class="section-colored">

        <div class="container">

            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 titulo-uno mycontent-left">
                    <h2>Valores:</h2>
                    <ul>
                        <li>Honestidad</li>
                        <ul>
                            <li>Nuestras políticas de trabajo se sustentan en la honestidad de nuestras propuestas y servicios prestados, todos en un marco de calidad</li>
                        </ul>
                        <li>Probidad</li>
                        <ul>
                            <li>La información proporcionada por nuestros clientes se maneja bajo los más estrictos protocolos de seriedad y cuidado de la misma.</li>
                        </ul>
                        <li>Responsabilidad</li>
                        <ul>
                            <li>Nuestros compromisos contractuales, formales e informales son cumplidos a cabalidad y además exigidos a nuestros colaboradores.</li>
                        </ul>
                    </ul>
                    
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 titulo-uno">
                    <h2>Compromisos:</h2>
                    <ul>
                        <li>Honestidad</li>
                        <ul>
                            <li>Nos comprometimos con los objetivos de nuestros clientes, asumiendo también acciones de involucramiento directo e indirecto en el cumplimiento de las tareas asignadas.</li>
                        </ul>
                        <li>Probidad</li>
                        <ul>
                            <li>Las tareas y procedimientos establecidos al interior de nuestra empresa se sustentan en principios de calidad internacional.</li>
                        </ul>
                        <li>Responsabilidad</li>
                        <ul>
                            <li>Nuestras labores, tareas y acciones son establecidas técnicas y operacionalmente con sustento en la seriedad de nuestro actuar y desarrollo profesional.</li>
                        </ul>
                    </ul>
                </div>
            </div>
            <!-- /.row -->

        </div>
        <!-- /.container -->

    </div>
    <!-- /.section-colored -->
<!--
    <div class="section">

        <div class="container">

            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <img class="img-responsive" src="http://placehold.it/700x450">
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <h2>Modern Business Features Include:</h2>
                    <ul>
                        <li>Bootstrap 3 Framework</li>
                        <li>Mobile Responsive Design</li>
                        <li>Predefined File Paths</li>
                        <li>Working PHP Contact Page</li>
                        <li>Minimal Custom CSS Styles</li>
                        <li>Unstyled: Add Your Own Style and Content!</li>
                        <li>Font-Awesome fonts come pre-installed!</li>
                        <li>100% <strong>Free</strong> to Use</li>
                        <li>Open Source: Use for any project, private or commercial!</li>
                    </ul>
                </div>
            </div>
           

        </div>
        

    </div>-->
    <!-- /.section -->
    <hr>
    <div class="container">

        <div class="row well">
            <div class="col-lg-8 col-md-8">
                <h4>¿Deseas mas informacion sobre nuestra empresa?</h4>
                <p>Ve al formulario de contacto! Rellena nuestro formulario te responderemos a la brevedad</p>
                
            </div>
            <div class="col-lg-4 col-md-4">
                <a class="btn btn-lg btn-primary pull-right" href="<?php echo $this->url('sitio-contacto') ?>">Contactanos!</a>
            </div>
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->